package com.HappyEsayGo.TestScript;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class SampleTestScriptOfHappyEasyGo {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@Before
public void setUp() {
 driver = new FirefoxDriver();
 js = (JavascriptExecutor) driver;
 vars = new HashMap<String, Object>();
}
@After
public void tearDown() {
 driver.quit();
}
@Test
public void happyeasygo() {
 driver.get("https://www.happyeasygo.com/");
 driver.manage().window().setSize(new Dimension(817, 522));
 driver.findElement(By.cssSelector(".f-icon")).click();
 driver.findElement(By.cssSelector(".roundtrip > .radio")).click();
 driver.findElement(By.cssSelector(".oneway > .radio")).click();
 driver.findElement(By.cssSelector(".roundtrip i")).click();
 driver.findElement(By.id("D_city")).click();
 driver.findElement(By.id("D_city")).sendKeys("chennai");
 driver.findElement(By.cssSelector("#ui-1 > .item")).click();
 driver.findElement(By.id("A_city")).click();
 driver.findElement(By.id("A_city")).sendKeys("bang");
 driver.findElement(By.cssSelector("#ui-1 > .active")).click();
 driver.findElement(By.id("D_date")).click();
 driver.findElement(By.linkText("1")).click();
 driver.findElement(By.linkText("11")).click();
 driver.findElement(By.id("pIcon")).click();
 driver.findElement(By.cssSelector(".A-passenger .plus-img")).click();
 driver.findElement(By.cssSelector(".C-passenger .plus-img")).click();
 driver.findElement(By.cssSelector(".I-passenger .plus-img")).click();
 driver.findElement(By.id("prenium")).click();
 driver.findElement(By.id("confirm")).click();
}
}

//driver.findElement(By.xpath(prop.readPropertiesFile("locators.textbox.to"))).sendKeys(Keys.TAB);

/*
* Click.ClickOnElement(driver,
* prop.readPropertiesFile("locators.pass.button"));
* 
* Click.ClickOnElement(driver,
* prop.readPropertiesFile("locators.pass.adults"));
* 
* Click.ClickOnElement(driver,
* prop.readPropertiesFile("locators.pass.children"));
* 
* Click.ClickOnElement(driver,
* prop.readPropertiesFile("locators.pass.infant"));
* 
* Click.clickOnElementById(driver,
* prop.readPropertiesFile("locators.radio.premium"));
* 
* Click.clickOnElementById(driver,
* prop.readPropertiesFile("locators.confirm.button"));
* 
* Click.ClickOnElement(driver,
* prop.readPropertiesFile("locators.select.ddate"));
* 
* Click.ClickOnElement(driver,
* prop.readPropertiesFile("locators.select.exactdddate"));
* 
* Click.ClickOnElement(driver,
* prop.readPropertiesFile("locators.select.rdate"));
* 
* Click.ClickOnElement(driver,
* prop.readPropertiesFile("locators.select.exactrdate"));
*/

/*
 * Click.SendkeysOnElement(driver, prop.readPropertiesFile("locators.dob.date"),
 * 5);
 * 
 * Click.SendkeysOnElement(driver,
 * prop.readPropertiesFile("locators.dob.month"), 6);
 * 
 * Click.SendkeysOnElement(driver, prop.readPropertiesFile("locators.dob.year"),
 * 7);
 * 
 */		/*
 * @Test(priority = 3) public void DepautureCbhome() throws InterruptedException
 * {
 * 
 * Click.ClickOnElement(driver, "(//span[@class='mark-bg mark1'])[1]"); }
 * 
 * @Test(priority = 4) public void DepautureCbDest() throws InterruptedException
 * {
 * 
 * Click.ClickOnElement(driver, "(//span[@class='mark-bg mark1'])[2]"); }
 */

